# -*- coding: utf-8 -*-
"""MLP-Perceptron_Multicamadas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eFRJUQtqGsv0KFmI_qFJUoCvD7pXTnmx
"""

import numpy as np

def sigmoid (soma):
   return 1/(1+np.exp(-soma))

def sigmoidDerivada (sig):
   return sig*(1-sig)

#sigmoid(-0.5)

#sigmoid(1.5)
#sigmoid(0.358)

entradas = np.array([[0,0], [0,1], [1,0], [1,1]])
saidas = np.array([[0], [1], [1], [0]])

#pesos0 = np.array([[-0.424, -0.740, -0.961], [0.358, -0.577, -0.469]])
#pesos1 = np.array([[-0.017], [-0.893], [0.148]])

pesos0 = 2*np.random.random((2,3)) - 1
pesos1 = 2*np.random.random((3,1)) - 1

epocas = 4998

momento = 1
taxaAprendizagem = 0.5

for j in range(epocas):
   camadaEntrada = entradas
   somaSinapse0 = np.dot(camadaEntrada, pesos0)
   camadaOculta = sigmoid(somaSinapse0)
   somaSinapse1 = np.dot(camadaOculta, pesos1)
   camadaSaida = sigmoid(somaSinapse1)
   #print(camadaSaida)

   erroCamadaSaida = saidas-camadaSaida
   mediaAbsoluta=np.mean(np.abs(erroCamadaSaida))
   print("Erro: " + str(mediaAbsoluta))

   derivadaSaida = sigmoidDerivada(camadaSaida)
   deltaSaida = erroCamadaSaida*derivadaSaida

   #preciso da transposta para fazer a multiplicacao da saida pelos, o .T faz isso?
   pesos1Transposta=pesos1.T
   deltaSaidaXPeso=deltaSaida.dot(pesos1Transposta)
   deltaCamadaOculta=deltaSaidaXPeso * sigmoidDerivada(camadaOculta)

   camadaOcultaTransposta = camadaOculta.T
   pesosNovo1 = camadaOcultaTransposta.dot(deltaSaida)
   pesos1 = (pesos1 * momento) + (pesosNovo1 * taxaAprendizagem)

   camadaEntradaTransposta = camadaEntrada.T
   pesosNovo0 = camadaEntradaTransposta.dot(deltaCamadaOculta)
   pesos0 = (pesos0 * momento) + (pesosNovo0 * taxaAprendizagem)

import math
entradas1 = np.array([[0,0]])
camadaEntrada = entradas1
somaSinapse0 = np.dot(camadaEntrada, pesos0)
camadaOculta = sigmoid(somaSinapse0)
somaSinapse1 = np.dot(camadaOculta, pesos1)
camadaSaida = sigmoid(somaSinapse1)
saidas1 = np.array([[0]])
erroCamadaSaida=saidas1-camadaSaida
print(saidas1,camadaSaida,erroCamadaSaida)